config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :kids, only: [:index, :new, :create, :show] do
    member do
      get :select
    end

    resources :disease_records, only: [:new, :create] do
      member do
        get :end_form
        patch :end_update
      end
    end

    resources :reported_symptoms, only: [:new, :create] do
      collection do
        post :start_record
        get :summary
      end
    end
  end
  
  # get "signup", to: "users#new"
  # ↓今後rootをpages/homeに変更予定
  root to: redirect('/users/sign_in')
  get "pages/home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/kid.rb
class Kid < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length: { maximum: 50 }

  validates :birthday, presence: true

  has_many :disease_records, dependent: :destroy
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :authenticate_user!

  def new
    @kid = Kid.new
  end

  def create
    @kid = current_user.kids.build(kid_params)
    if @kid.save
      redirect_to kids_path, notice: '登録しました.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @kids = current_user.kids
  end

  def select
    @kid = current_user.kids.find(params[:id])
    session[:current_kid_id] = @kid.id
    latest_record = @kid.disease_records.order(:start_at).last
  
    if latest_record.nil? || latest_record.end_at.present?
      redirect_to new_kid_reported_symptom_path(@kid, new_record: true)
    else
      redirect_to new_kid_reported_symptom_path(@kid, disease_record_id: latest_record.id)
    end
  end

  def show
    @kid = current_user.kids.find(params[:id])
    @disease_records = @kid.disease_records.order(start_at: :desc)
  end

  private

  def kid_params
    params.require(:kid).permit(:name, :birthday)
  end
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/views/kids/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>medical record - お子さま一覧</title>
</head>
<body>
  <main class="login-main">
    <ul>
      <% @kids.each do |kid| %>
        <li>
          <%= link_to kid.name, select_kid_path(kid), class: "kid-link" %>
        </li>
       <% end %>
    </ul>

    <div class="form-actions">
        <%= link_to "新規登録", new_kid_path,class: "login-button" %>
    </div>
  </main>
</body>
</html>

app/views/kids/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>medical record - お子さま登録</title>
</head>
<body>
  <main class="login-main">
    <%= render "shared/error_messages", object: @kid %>

    <%= form_for(@kid, url: kids_path, html: { class: "login-form" }) do |f| %>
      
      <!-- 子どもの名前 -->
      <div class="form-group">
        <%= f.label :name, "お子さまの名前" %>
        <%= f.text_field :name, autofocus: true, class: "form-control" %>
      </div>

      <!-- 生年月日 -->
      <div class="form-group">
        <%= f.label :birthday, "生年月日" %>
        <%= f.date_field :birthday, class: "form-control" %>
      </div>

      <div class="form-actions">
        <%= f.submit "登録", class: "login-button" %>
      </div>
    <% end %>
  </main>
</body>
</html>

app/views/kids/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>medical record - 症状記録</title>
</head>
<body>
  <main class="login-main">

    <p>看病お疲れ様でした！！！</p>

    <!-- フッター -->
    <div class="footer">
      <p>
        <%= @kid.name %>
      </p>
    </div>
  </main>
</body>
</html>