config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :kids, only: [:index, :new, :create, :show] do
    member do
      get :select
    end

    resources :disease_records, only: [:new, :create] do
      member do
        get :end_form
        patch :end_update
      end
    end

    resources :reported_symptoms, only: [:new, :create] do
      collection do
        post :start_record
        get :summary
      end
    end
  end
  
  # get "signup", to: "users#new"
  # ↓今後rootをpages/homeに変更予定
  root to: redirect('/users/sign_in')
  get "pages/home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Medical Record App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload", media: "all" %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= javascript_importmap_tags %>
    <%= yield :head %>
  </head>

  <body>
  <header class="site-header">
    <h2>medical record</h2>
    <nav class="nav-menu">
      <% if user_signed_in? %>
        <% if current_kid.present? %>
          <%= link_to "記録", new_kid_reported_symptom_path(current_kid), class: "nav-button" %>
          <%= link_to "サマリー", summary_kid_reported_symptoms_path(current_kid), class: "nav-button" %>
        <% end %>
        <%= button_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-button" %>
      <% end %>
    </nav>
  </header>

    <%= yield %>
  </body>
</html>